### ISSUE TITLE
Values not showing up

### ISSUE THREAD

**Issue by Rogerforver** [okviz/calendar-pro-issues#8]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Noob Question

I'm creating a simple adherence report -  The Calendar pro is filtering the dates but its not showing the values as a color filled dates in the calendar . 

Please refer pic below.  Basically, I'm trying to get the chart appear inside your custom calendar visual and when I select a data it can filter that day for the rest of the visuals in the page which is working! the only thing missing are my values. Please advise.
![image (1)](https://github.com/okviz/calendar-pro-issues/assets/136851781/0e955d41-37cd-4785-9f49-a93b087e426c)

### Power BI

Power BI Desktop

### Power BI Version

Version: 2.118.621.0 64-bit (June 2023)

### Steps To Reproduce

Added the Calendar Pro Visual 
Loaded a simple Excel Data
Added Date from the table into the Calendar Pro data panel
Added Value column "Total Meeting" measure - simple count of meetings
No Changes to the report. 

I have added the pbix file 

### Sample report

[sample report.zip](https://github.com/okviz/calendar-pro-issues/files/11774235/sample.report.zip)

### Screenshot

![image (1)](https://github.com/okviz/calendar-pro-issues/assets/136851781/b01126bf-e579-4743-a445-52ef023deb5d)

**Comment by Rogerforver** [comment]
I'm trying to get the chart appear inside your custom calendar visual and when I select a date* it  filters that day for the rest of the visuals in the page which is great! the only thing missing are my values. Please advise.

**Comment by Rogerforver** [comment]
NVM it works if we use date table from power bi instead of data table. Thank you
![image](https://github.com/okviz/calendar-pro-issues/assets/136851781/b5459e1f-9358-41ab-895f-f3a73961c479)

**Comment by marcosqlbi** [comment]
Please, can you clarify what did you change? From the first screenshot, it seems you were already using a date table from Power BI and you had the Auto Date/Time feature enabled. Even though this should not be required, it should have worked.  The visual should work in both cases, perhaps, the problem is that you had date & time in the same column whereas you should have had only date so that the aggregation by day would return the total of meetings by day.

**Comment by Rogerforver** [comment]
Yes you are right.  After creating a Dax Calendar table since I was going to bring in some dim table.  At that time I also changed my data table's date type from date & time to date in power query,  When I previously changed the data type in the Data panel it dint work.

**Comment by marcosqlbi** [comment]
Ok thanks for the feedback. The best way to understand what is going on is to change from Calendar to Table or Matrix and see the underlying data, next time do that to check that the time is not included - you also would have seen multiple rows for the same day (because of different time).
Thanks for the feedback!

**Comment by Rogerforver** [comment]
Thank you for the tip!
"you also would have seen multiple rows for the same day (because of different time)." yes!!!
Really nice visual. Would love to see a video to unlock its full potential.

We will be subscribing for this visual shortly
